---
- name: setup backup script for project
  template:
    src: duplicitybkp_s3.sh.j2
    dest: "{{ backup_dir }}/{{ backup_name }}/duplicitybkp_s3.sh"
    mode: 0700
    owner: root
    group: root

- name: setup exclude.list for project
  template:
    src: exclude.list.j2
    dest: "{{ backup_dir }}/{{ backup_name }}/exclude.list"
    mode: 0700
    owner: root
    group: root

- name: duplishift log rotation
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/duplicitybkp
    owner: root
    group: root
    mode: 0644

- name: add cron job
  cron:
    name: make {{ backup_name }} s3 backup
    minute: "06"
    hour:   "2"
    job:    "{{ backup_dir }}/{{ backup_name }}/duplicitybkp_s3.sh >{{ backup_dir }}/{{ backup_name }}/duplicity.log 2>&1"
