---

# fixme
# check dirs exist

- name: duplicitybkp_ssh | ssh_store_path
  become: no
  ansible.builtin.debug:
    var: duplicitybkp_ssh_store_path
    verbosity: 1

- name: duplicitybkp_ssh | store directory exists
  become: no
  file:
    path: "{{ duplicitybkp_ssh_store_path }}"
    state: directory
    mode: "0755"
  delegate_to: "{{ duplicitybkp_ssh_store_hostname }}"
  tags: [duplicitybkp_ssh, duplicitybkp_ssh_target]


- name: duplicitybkp_ssh | set variables
  set_fact:
    _duplicitybkp_extraopts: "{{ duplicitybkp_extraopts + ' ' + duplicitybkp_ssh_extraopts }}"
  tags: [duplicitybkp_ssh, duplicitybkp_ssh_script]

- name: duplicitybkp_ssh | setup backup script for project
  template:
    src: duplicitybkp_ssh.sh.j2
    dest: "{{ duplicitybkp_ssh_bin_fullname }}"
    mode: 0700
    owner: root
    group: root
  tags: [duplicitybkp_ssh, duplicitybkp_ssh_script]

- name: duplicitybkp_ssh | setup exclude list for project
  template:
    src: duplicitybkp_ssh_exclude.list.j2
    dest: "{{ duplicitybkp_ssh_exclude_fullname }}"
    mode: 0644
    owner: root
    group: root
  when:
    - duplicitybkp_ssh_execlude_list is defined
    - duplicitybkp_ssh_execlude_list | length > 0
  tags: [duplicitybkp_ssh, duplicitybkp_ssh_exclude]

- name: duplicitybkp_ssh | configure log rotation
  template:
    src: duplicitybkp_ssh_logrotate.j2
    dest: "/etc/logrotate.d/{{ duplicitybkp_ssh_logrotated_filename }}"
    mode: 0644
    owner: root
    group: root
  tags: [duplicitybkp_ssh]

- name: duplicitybkp_ssh | add cron job for run duplicity
  cron:
    name: "make {{ duplicitybkp_ssh_jobname }} ssh duplicity backup"
    minute: "06"
    hour:   "2"
    job:    "{{ duplicitybkp_ssh_bin_fullname }} >{{ duplicitybkp_ssh_log_fullname }} 2>&1"
  tags: [duplicitybkp_ssh]
