---
- name: ensure bin directory exists
  file:
    path: "{{ mysqlbkp_bin_path }}"
    state: directory
  tags: mysqlbkp_install

- name: script setup
  template:
    src: "mysqlbkp_fullcfg.sh.j2"
    dest: "{{ mysqlbkp_bin_name }}"
    mode: 0750
    owner: "root"
    group: "root"
  tags: mysqlbkp_install

- name: cronjob create
  cron:
    name: "mysql backup by list"
    minute: "03"
    hour: "0"
    job: "{{ mysqlbkp_bin_name }} >{{ mysqlbkp_log_name }} 2>&1"
  tags: mysqlbkp_install

- name: logrotate mysqlbkp
  template:
    src: "mysqlbkp.logrotate.j2"
    dest: "/etc/logrotate.d/{{ mysqlbkp_logrotate_name }}"
    mode: 0644
    owner: "root"
    group: "root"
  tags: mysqlbkp_install
