---
- name: ensure config directory exists
  file:
    path: "{{ mysqlbkp_config_path }}"
    state: directory

- name: create configfile for backup
  lineinfile:
    path: "{{ mysqlbkp_config_name }}"
    regexp: "{{ mysqlbkp_db }}.*"
    line: "{{ mysqlbkp_db }} {{ mysqlbkp_data_path }} {{ mysqlbkp_host }} {{ mysqlbkp_port }} {{ mysqlbkp_user }} {{ mysqlbkp_pass }}"
    create: true
