---
# defaults file for backup
bkp_name: "test"
backup_user: "backup"
mysqlbkp_user: "bkp"
mysqlbkp_pass: "{{ lookup('password', 'credentials/' + mysqlbkp_host + '/mysql_bkp_password length=14 chars=ascii_letters,digits,hexdigits') }}"
mysqlbkp_compress: false

duplicitybkp_packages_list_pip:
  - python-keystoneclient==5.2.0
  - python-swiftclient==4.4.0
  - fasteners==0.19
  - duplicity==2.2.1


duplicitybkp_pip_path: /srv/python3.10/bin/pip3.10
duplicitybkp_duplicity_path: /usr/bin/duplicity
duplicitybkp_bin_type: deb

duplicitybkp_path: "/usr/local"
backup_dir: "{{ duplicitybkp_path }}"
duplicitybkp_bin_path:  "{{ duplicitybkp_path }}/bin"
duplicitybkp_cfg_path:  "{{ duplicitybkp_path }}/etc"
duplicitybkp_data_path: "{{ duplicitybkp_path }}/data"
duplicitybkp_log_path:  "{{ duplicitybkp_path }}/log"


duplicitybkp_swift_tenantname: "{{ backup_swiftuser }}"   #project_name
duplicitybkp_swift_authurl: "https://api.selcdn.ru/v2.0"
duplicitybkp_swift_auth_version: 2

duplicitybkp_swift_userdomain: ""
duplicitybkp_swift_projectdomain: ""


mysqlbkp_jobname_prefix: ""
mysqlbkp_config_path:    "{{ duplicitybkp_cfg_path  }}"
mysqlbkp_config_name:    "{{  mysqlbkp_config_path  }}/{{ mysqlbkp_jobname_prefix|default('') }}_mysql"
mysqlbkp_data_path:      "{{ duplicitybkp_data_path }}/{{ mysqlbkp_jobname_prefix|default('') }}_mysql"
mysqlbkp_bin_path:       "{{ duplicitybkp_bin_path  }}"
mysqlbkp_bin_name:       "{{     mysqlbkp_bin_path  }}/{{ mysqlbkp_jobname_prefix|default('') }}_mysql.sh"
mysqlbkp_log_path:       "{{ duplicitybkp_log_path  }}"
mysqlbkp_log_name:       "{{     mysqlbkp_log_path  }}/{{ mysqlbkp_jobname_prefix|default('') }}_mysql.log"
mysqlbkp_logrotate_name: "{{ mysqlbkp_jobname_prefix|default('') }}_mysql"

duplicitybkp_sshkey_jobname_prefix: "{{ bkp_name }}"
duplicitybkp_sshkey_config_path:    "{{ duplicitybkp_cfg_path }}"
duplicitybkp_sshkey_name:           "{{ duplicitybkp_sshkey_config_path }}/{{ duplicitybkp_sshkey_jobname_prefix|default('') }}_id"

duplicitybkp_ssh_jobname_prefix:   "{{ bkp_name }}"
duplicitybkp_ssh_jobname:          "{{ duplicitybkp_ssh_jobname_prefix|default('') }}_duplicitybkp_ssh"

duplicitybkp_ssh_bin_path:         "{{ duplicitybkp_bin_path }}"
duplicitybkp_ssh_config_path:      "{{ duplicitybkp_cfg_path }}"
duplicitybkp_ssh_log_path:         "{{ duplicitybkp_log_path }}"

duplicitybkp_ssh_bin_name:         "{{ duplicitybkp_ssh_jobname }}.sh"
duplicitybkp_ssh_bin_fullname:     "{{ duplicitybkp_ssh_bin_path    }}/{{ duplicitybkp_ssh_bin_name     }}"
#duplicitybkp_ssh_exclude_list:    ""
duplicitybkp_ssh_exclude_name:     "{{ duplicitybkp_ssh_jobname }}_exclude"
duplicitybkp_ssh_exclude_fullname: "{{ duplicitybkp_ssh_config_path }}/{{ duplicitybkp_ssh_exclude_name }}"
duplicitybkp_ssh_log_name:         "{{ duplicitybkp_ssh_jobname }}.log"
duplicitybkp_ssh_log_fullname:     "{{ duplicitybkp_ssh_log_path    }}/{{ duplicitybkp_ssh_log_name     }}"

duplicitybkp_ssh_logrotae_name:    "{{ duplicitybkp_ssh_jobname }}"
duplicitybkp_ssh_logrotated_filename: "{{ duplicitybkp_ssh_jobname }}"
duplicitybkp_ssh_logrotate_rule:   "{{ duplicitybkp_ssh_log_fullname }}"

duplicitybkp_ssh_backup_target: "{{ duplicitybkp_data_path }}"

duplicitybkp_ssh_store_proto: "rsync"
#duplicitybkp_ssh_store_user: ""
#duplicitybkp_ssh_store_host: ""
duplicitybkp_ssh_store_hostname: "{{ duplicitybkp_ssh_store_host }}"
duplicitybkp_ssh_store_path: "{{ duplicitybkp_ssh_jobname_prefix }}"
duplicitybkp_ssh_store_dsn: "{{ duplicitybkp_ssh_store_proto }}://{{ duplicitybkp_ssh_store_user }}@{{ duplicitybkp_ssh_store_host }}/{{ duplicitybkp_ssh_store_path }}"

#duplicitybkp_scritptemplate
duplicitybkp_type: swift
duplicitybkp_volsize: 500
duplicitybkp_removeolder: "31D"
duplicitybkp_fullcopies: "3"
duplicitybkp_extraopts: ""


#duplicitybkp_ssh_scritptemplate only ssh
duplicitybkp_ssh_extraopts: "--rsync-options=\"-e'ssh -oIdentityFile={{ duplicitybkp_sshkey_name }}'\""

duplicitybkp_s3_endpoint: "{{ '--s3-endpoint-url=' ~ duplicitybkp_s3_endpoint_url if duplicitybkp_s3_endpoint_url|length > 0  else '' }}"
duplicitybkp_s3_region: "{{ '--s3-region-name=' ~ duplicitybkp_s3_region_name if duplicitybkp_s3_region_name|length > 0  else '' }}"
duplicitybkp_s3_opts: "{{ duplicitybkp_s3_endpoint }} {{ duplicitybkp_s3_region }}"
# duplicitybkp_s3_bucket
# duplicitybkp_s3_accesskey
# duplicitybkp_s3_secretkey



